README.md
>  Vue+Viteプロジェクトの作成手順追加
> 正常にサーバ起動するかどうか
> ソースコードに対して、以下のチェックを実施する。
> 補足情報があれば記載。
=> README.mdにプロジェクト作成手順追加

.gitignore, package-lock.json, package.json, prisma/schema.prisma
prismaのインストールをしました。
初期化までしています。
インストールできているか
> 補足情報があれば記載。
=> prismaインストール・初期化

README.md
データベース作成とPrismaの接続に関して記載しました。
手順で抜けていることはないか
> 補足情報があれば記載。
=> READMEにDBとPrismaに関して追加

package-lock.json, prisma/migrations/20241225025201_/migration.sql, prisma/migrations/20241225044603_/migration.sql, prisma/schema.prisma
> schema.prismaにmodel追加
> 補足情報があれば記載。
=> schema.prismaにmodel追加

prisma/migrations/20241225050035_table_name_fixed/migration.sql, prisma/schema.prisma
Userのスペル修正と削除をしました。
スペルミスがないか
> 補足情報があれば記載。
=> データモデルのスペル変更と削除

package-lock.json, package.json, prisma/seed.ts, tsconfig.app.json
> 仮データ追加用ファイル（seed.ts）をprismaディレクトリ内に作成した。
> 補足情報があれば記載。
=> 仮データ追加用ファイル作成

prisma/migrations/20250106015046_achivement_progress_fixed/migration.sql, prisma/migrations/20250106015620_diary_date_fixed/migration.sql, prisma/schema.prisma, prisma/seed.ts
スキーマの修正をしました。（progress、date）
仮のデータを一部追加しました。
データに問題ないか。
スキーマの型は間違えていないか
> 補足情報があれば記載。
=> 仮データの追加、スキーマ修正

prisma/seed.ts
> seed.tsに仮データ追加
> データ数は合っているか
> データが正しく反映されるか
> 補足情報があれば記載。
=> seed.tsに仮データ追加

src/components/Title.vue
> Titleコンポーネントの作成
> Titleコンポーネントの内容確認
#13 
> 補足情報があれば記載。
=> Titleコンポーネントの作成

src/components/Footer.vue
Footerを作成しました。
画像にリンク必要？
CSSなど問題ないか確認お願いします。
- #10 
> 補足情報があれば記載。
=> #10 Footerの作成

package-lock.json, package.json, src/App.vue, src/components/CreateUserForm.vue, src/components/Home.vue, src/main.ts, src/router/index.ts
> 新規会員登録フォームの側だけ作成、Vue Routerを使用した簡単な遷移
> 補足情報があれば記載。
=> 新規会員登録フォーム（側だけ）＆簡単な遷移

api-document.yml, package-lock.json, package.json
> api設計書をプロジェクトに入れて見れるようにした。
> 補足情報があれば記載。
=> api設計書をプロジェクトに入れただけ

src/App.vue, src/components/Button.vue, src/components/NicknameForm.vue, src/router/index.ts
NicknameFormコンポーネントを作成しました。
Buttonコンポーネントを作成しました。
VueRouterを使ってるのでpathを指定してます。
データの送信はまだできないので側だけです。
VueRouterの使い方など問題ないか確認お願いします。
- #12 
- #21 
> 補足情報があれば記載。
=> #12#21 NicknameFormとButtonコンポーネントの作成

src/App.vue, src/api/server.ts, src/components/Setting.vue, src/pages/SettingPage.vue, src/router/index.ts
> 設定ページ作成（SettingPage.vue,Setting.vue）
> server.tsのconsole.log削除
> 補足情報があれば記載。
=> 設定ページ作成（側だけ）

src/api/nickname.ts, src/components/Button.vue, src/components/NicknameForm.vue
- NicknameFormでUserのnicknameを上書きできるようにしました。
- Buttonコンポーネントの影響でfetchができなかったので修正しました
- Buttonコンポーネントでpageの遷移は不要かどうか
#12 #21 
> 補足情報があれば記載。
=> NicknameFormとButtonコンポーネントの修正

src/App.vue
> コンフリクト解消時誤って削除したキャラクター選択のrouterlinkを戻した。
> 補足情報があれば記載。
=> Fix selectcharacter

src/App.vue, src/components/DatePagination.vue, src/components/Setting.vue, src/pages/AnalysisResult.vue, src/router/index.ts
> DatePagenationコンポーネント作成
> Settingのinputタグに必要なid,name要素が抜けていたため追加
> 矢印クリック時に年月が変わるか
#
> 補足情報があれば記載。
=> 感情分析結果確認画面のページネーション作成

src/api/select_character_api.ts, src/components/SelectCharacter.vue
- selectCharacterの機能実装をしました。（キャラクター選択時にUserのcharacter_idが上書きされる）
画像データをDBに保存した際に変更が必要。
- nickname.tsのlocalhostの部分の空白を埋めました。
コードミスがないか
#23
> 補足情報があれば記載。
=> #23 selectCharacterの機能実装

package-lock.json, package.json, src/App.vue, src/components/DiaryNav.vue, src/main.ts, src/pages/NicknamePage.vue, src/plugins/vuetify.ts, src/router/index.ts
-  Vuetifyの追加（material Iconの使用のため）
- Diaries Pageの確認のためにApp.tsにリンクを追加
- DiaryNavコンポーネントの側だけ作成（アイコンに機能実装必要）
- Nickname Pageをコンポーネントとしてpagesに追加
不必要なファイルやコードはないか確認してください
#27 
> 補足情報があれば記載。
=> #27 DiaryNavコンポーネントの作成

src/api/header.ts, src/components/Date.vue, src/components/DatePagination.vue, src/components/Header.vue, src/components/NickName.vue, src/components/TodayFace.vue, src/components/TodayGoal.vue, src/server.ts, src/shims-vue.d.ts
> - <script> → <script setup lang="ts">変更、server.tsに移動によるコード修正
> - <style> → <style scoped>に修正
> - shims-vue.d.tsファイルの追加（詳しくは補足情報へ）
vueファイルをimportしようとするとエラーが出ていた。
.vueファイルをどう解釈するか教える型宣言。TypeScript は .ts や .js ファイルに対しては型のチェックができるが、.vue ファイルはデフォルトでは型チェックの対象外なので、この宣言を使って .vue ファイルの扱い方を指定する。
参考文献↓
https://qiita.com/raratyurara/items/3ec1d78bebb76bde641a
=> server.tsに移動、Headerコンポーネント関連の修正

prisma/migrations/20250122012051_add_required_columns/migration.sql, prisma/migrations/20250122013321_fix_achievement_table/migration.sql, prisma/schema.prisma, prisma/seed.ts
> ahievementテーブル修正
> 補足情報があれば記載。
=> achievementテーブル修正

src/api/settingNewNickName.ts, src/components/Setting.vue, src/pages/LoginPage.vue, src/server.ts, src/style.css
> 音楽onoffをlocalStorageに反映
> ニックネームを更新時、データベース、ヘッダーに反映
> ニックネーム変更画面ではヘッダーのニックネーム表示は変わらず、リロードすると新しいニックネームに変わります。同時に変わるようにする？
> LoginPage.vueはエラーが出ていたため書き方を変更
> 補足情報があれば記載。
=> 設定画面の音楽とニックネームを実装

src/api/diaries.ts, src/components/DiaryForm.vue, src/pages/DiaryPage.vue, src/router/index.ts, src/server.ts
- フォームに入力した内容がDBに保存されるようにしました。
- 見た目はまだ修正かけてないです
データの保存時の内容に間違いはないか
#28 
> 補足情報があれば記載。
=> 日記入力フォームの保存

src/components/CreateUserForm.vue
> 新規会員登録画面の入力内容を送信前に確認するモーダルを作成中。
ほとんど何もしてないけどプッシュしておきます。
> 補足情報があれば記載。
=> 入力確認モーダル作ってる途中
